project:
  type: website

website:
  title: "End to End Projects"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sumendar
      - icon: twitter
        href: https://twitter.com/sumendar
format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    
editor: visual

